name: assistant
version: 87.0.0+87
publish_to: 'none'
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  ffi: 2.1.4
  path: 1.9.1
  async: 2.13.0
  collection: 1.19.1
  decimal: 3.2.4
  provider: 6.1.5
  path_provider: 2.1.5
  material_symbols_icons: 4.2858.1
  window_manager: 0.5.1
  dynamic_color: 1.8.1
  url_launcher: 6.3.2
  app_links: 6.4.0
  file_selector: 1.0.3
  flutter_local_notifications: 19.4.0
  super_drag_and_drop: 0.9.1
  single_child_two_dimensional_scroll_view: 0.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
flutter:
  uses-material-design: true
  assets:
    - asset/
